# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39b249c1604e106606ca3079c2ca8e5e6cf4606d0530a1458ba57eadf7c6d9913c88bd22c9e22e328d2f676711de609d9062b08c1c17da2f0a926b5d4984dd76

test:
  secret_key_base: 0c0739952c5f67faafa682e4f0c294840cfc10025c93d78f9b92e8633536b96289fff3a30687b19396ae063e4e8c059b04c27b58fd23c3d6743f120e99ad6d1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
